name: Deploy Public API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ana3lu/public-api
      HELM_MANIFESTS_REPO: https://github.com/Ana3Lu/k8s-manifests.git
      BRANCH_HELM: 'main'

    steps:
      - name: Checkout API Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: chmod +x ./gradlew && ./gradlew build

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ github.sha }}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Clone Helm Manifests Repository (main branch)
        run: |
          git clone --single-branch --branch ${{ env.BRANCH_HELM }} ${{ env.HELM_MANIFESTS_REPO }} helm-manifiestos

      - name: Install yq
        uses: mikefarah/yq@v4.44.3

      - name: Update values.yaml with new image tag
        run: |
          cd helm-manifiestos/helm-chart-api/public-api
          yq eval '.image.tag = "${{ github.sha }}"' -i values.yaml

      - name: Commit and Push updated values.yaml to k8s-manifests
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          cd helm-manifiestos
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.GH_ACCESS_TOKEN }}@github.com/Ana3Lu/k8s-manifests.git
          git add helm-chart-api/public-api/values.yaml
          git commit -m "Update image tag in Helm values.yaml to ${{ github.sha }}"
          git push origin ${{ env.BRANCH_HELM }}
